# Channel indices for raw and seg images
# Note: membrane in raw and cell_seg in seg are required
# All others are optional and their names can be changed
channels:
        raw_channels:
                nucleus: 0
                membrane: 1


        seg_channels:
                nuc_seg: 0
                cell_seg: 1


# Directory in which to save results
# Individual steps will create their own subdirs to save within this
project_dir: '/path/to/project_dir'

# Directory containing raw images
raw_dir: '/path/to/raw_dir'

nucleus_segmentation:
        # enable/disable nucleus segmentation step
        state: False
        # path to directory with nucleus mask predictions
        nuc_pred_dir: '/path/to/nuc_pred_dir'
        nuc_pred_threshold: 0.6
        # parameters for distance transform watershed
        sigma: 6
        min_distance: 12
        # whether to use boundary predictions for nucleus splitting
        split_nuclei:
                state: True
                boundary_dir: '/path/to/boundary_dir'
                mem_pred_threshold: 0.4
                # set mode to automatic or interactive
                mode: 'automatic'
        output_dir: '/path/to/output_dir'

membrane_segmentation:
        # enable/disable membrane segmentation step
        state: False
        # path to nuclear labels
        nuc_labels_dir: '/path/to/nuc_labels_dir'
        # path to directory with membrane boundary predictions
        mem_pred_dir: '/path/to/mem_pred_dir'
        # desired output directory name (will be created if nonexistent)
        output_dir: '/path/to/output_dir'

create_fov_dataset:
        # enable/disable fov dataset creation
        state: True
        # directory with original .czi images to get pixel size
        original_dir: '/path/to/original_dir'
        # directory with segmented/label images
        seg_dir: '/path/to/seg_dir'
        # set autorotation and, if so, the strategy to use
        autorotate: False

prep_single_cells:
        # enable/disable single cell dataset creation from fov dataset
        state: True

alignment:
        # enable/disable alignment
        state: True
        # allow to continue from previous partially completed run
        continue_from_previous: False
        # channel in the seg img to use to calculate the radial rotation angle
        rot_ch_index: 1
        # whether to make the rotation unique
        make_unique: True
        # alignment method to use
        # available modes: unaligned, xy_only, xy_xz, xy_xz_yz, principal_axes
        # see README for details
        mode: 'xy_xz_yz'
        # channels to use to calculate tilt correction angle(s)
        use_channels: '1'
        # use >45 degree angle correction
        45_corr_xz: False
        45_corr_yz: True
