# Channel indices for raw and seg images
channels:
        raw_channels:
                nucleus: 0
                membrane: 1

        seg_channels:
                nucleus_seg: 0
                cell_seg: 1

segmentation:
        # enable/disable instance segmentation step
        state: False
        # what to segment - cell, nuc, or cellnuc (both)
        structure: cellnuc
        # path to directory containing raw images to process
        raw_dir: '/home/maddy/projects/claudin_gfp_5dpf_DRAQ5_1h_airy_live_2_test_subset/stack_aligned'
        # path to nuclear mask predictions directory
        nuc_pred_dir: '/home/maddy/projects/claudin_gfp_5dpf_DRAQ5_1h_airy_live_2/nuc_model_iter2_results_checkpoint_100'
        nuc_pred_threshold: 0.6
        # if nuclei segs are already labeled images, set this to to True
        is_nuc_labeled: False
        # path to directory with membrane boundary predictions
        mem_pred_dir: '/home/maddy/projects/claudin_gfp_5dpf_DRAQ5_1h_airy_live_2/mem_model_3_results'
        mem_pred_threshold: 0.4
        # desired output directory name (will be created if nonexistent)
        output_dir: '/home/maddy/projects/claudin_gfp_5dpf_DRAQ5_1h_airy_live_2_test_subset'

create_fov_dataset:
        # enable/disable fov dataset creation
        state: True
        # directory with original .czi images to get pixel size
        original_dir: '/home/maddy/projects/claudin_gfp_5dpf_DRAQ5_1h_airy_live_2_test_subset/original'
        # directory with segmented/label images
        seg_dir: '/home/maddy/projects/claudin_gfp_5dpf_DRAQ5_1h_airy_live_2_test_subset/segmentations'
        # set autorotation and, if so, the strategy to use
        autorotate: False
        output_dir: '/home/maddy/projects/claudin_gfp_5dpf_DRAQ5_1h_airy_live_2_test_subset/cvapipe_run_TEST'
        file_ext: tiff

alignment:
        # enable/disable alignment
        state: False
        # channel to use to calculate the rotation angle
        rot_ch_index: 1
        # whether to make the rotation unique
        make_unique: True
        # alignment method to use (xy_only or xy_xz)
        mode: xy_xz
