# Channel indices for raw and seg images
# Note: membrane in raw and cell_seg in seg are required
# All others are optional and their names can be changed
channels:
        raw_channels:
                membrane: 0

        seg_channels:
                cell_seg: 0


# Directory in which to save results
# Individual steps will create their own subdirs to save within this
project_dir: '/home/maddy/projects/one_ch_test/cvapipe_run_TEST'

# Directory containing raw images
raw_dir: '/home/maddy/projects/one_ch_test/stack_aligned'

segmentation:
        # enable/disable instance segmentation step
        state: False
        # path to nuclear mask predictions directory
        nuc_pred_dir: '/home/maddy/projects/claudin_gfp_5dpf_DRAQ5_1h_airy_live_2/nuc_model_iter2_results_checkpoint_100'
        nuc_pred_threshold: 0.6
        # if nuclei segs are already labeled images, set this to to True
        is_nuc_labeled: False
        # path to directory with membrane boundary predictions
        mem_pred_dir: '/home/maddy/projects/claudin_gfp_5dpf_DRAQ5_1h_airy_live_2/mem_model_3_results'
        mem_pred_threshold: 0.4
        # desired output directory name (will be created if nonexistent)
        output_dir: '/home/maddy/projects/three_ch_test'

create_fov_dataset:
        # enable/disable fov dataset creation
        state: True
        # directory with original .czi images to get pixel size
        original_dir: '/home/maddy/projects/one_ch_test/original'
        # directory with segmented/label images
        seg_dir: '/home/maddy/projects/one_ch_test/segmentations'
        # set autorotation and, if so, the strategy to use
        autorotate: False

prep_single_cells:
        # enable/disable single cell dataset creation from fov dataset
        state: True

alignment:
        # enable/disable alignment
        state: True
        # channel to use to calculate the rotation angle
        rot_ch_index: 0
        # whether to make the rotation unique
        make_unique: True
        # alignment method to use (xy_only or xy_xz)
        mode: xy_xz
